name: config
version: 1.0.0
maintainer: falcon-devs
github: ""
license: ""
ffi:
  build/config-wrapper.so: sha256:d6822d400f09047484d405e6d2806e365cf2fccf496e3939e0f36c0d3b9b2566
dependencies:
  - name: connection
    version: 1.0.0
    local_path: ../deviceStructures/connection/
  - name: connections
    version: 1.0.0
    local_path: ../deviceStructures/connections/
  - name: impedance
    version: 1.0.0
    local_path: ../deviceStructures/impedance/
  - name: channel
    version: 1.0.0
    local_path: ../../autotunerInterfaces/names/channel/
  - name: channels
    version: 1.0.0
    local_path: ../../autotunerInterfaces/names/channels/
  - name: gname
    version: 1.0.0
    local_path: ../../autotunerInterfaces/names/gname/
  - name: farray
    version: 1.0.0
    local_path: ../../generic/farray/
  - name: array
    version: 1.0.0
    local_path: ../../../../collections/array/
  - name: testing
    version: 1.0.0
    local_path: ../../../../testing/