name: config
version: 1.0.0
maintainer: "falcon-devs"
github: ""
dependencies:
  - name: connection
    version: 1.0.0
    local_path: "../deviceStructures/connection/"
  - name: connections
    version: 1.0.0
    local_path: "../deviceStructures/connections/"
  - name: impedance
    version: 1.0.0
    local_path: "../deviceStructures/impedance/"
  - name: channel
    version: 1.0.0
    local_path: "../../autotunerInterfaces/names/channel/"
  - name: channels
    version: 1.0.0
    local_path: "../../autotunerInterfaces/names/channels/"
  - name: gname
    version: 1.0.0
    local_path: "../../autotunerInterfaces/names/gname/"
  - name: farray
    version: 1.0.0
    local_path: "../../generic/farray/"
  - name: array
    version: 1.0.0
    local_path: "../../../../collections/array/"
  - name: testing
    version: 1.0.0
    local_path: "../../../../testing/"

ffi:
  build/config-wrapper.so: sha256:b417de3390f8da1a049e532dd59a6f2a984947489239a6bace0b3039e1a05a1f
