name: config
version: 1.0.0
maintainer: falcon-devs
github: ""
license: ""
ffi:
  build/config-wrapper.so: sha256:bb127ee26f43c29d58bef872f0b73c409766241ee41bdfc5294f8dd748cba096
dependencies:
  - name: connection
    version: 1.0.0
    local_path: ../deviceStructures/connection/
  - name: connections
    version: 1.0.0
    local_path: ../deviceStructures/connections/
  - name: impedance
    version: 1.0.0
    local_path: ../deviceStructures/impedance/
  - name: channel
    version: 1.0.0
    local_path: ../../autotunerInterfaces/names/channel/
  - name: channels
    version: 1.0.0
    local_path: ../../autotunerInterfaces/names/channels/
  - name: gname
    version: 1.0.0
    local_path: ../../autotunerInterfaces/names/gname/
  - name: farray
    version: 1.0.0
    local_path: ../../generic/farray/
  - name: array
    version: 1.0.0
    local_path: ../../../../collections/array/
  - name: testing
    version: 1.0.0
    local_path: ../../../../testing/